import Head from 'next/head'
import Todo from '../components/Todo.jsx'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button hidden className='bg-green-400 ring-black ring-transparent'></button>
      <main className="container m-auto drop-shadow-lg">
        <Todo/>
      </main>
      
    </div>
  )
}
